name: tutoriais-python
channels:
    - conda-forge
dependencies:
    - python=3.*
    - pip
    - ipykernel
    - numpy
    - matplotlib
    - h5py
    - scipy
    - scikit-image
    - xarray
    - cartopy
    - arm_pyart
    - wradlib > 1.13
    - metpy
