name: tutoriais-python
channels: 
    - conda-forge
dependencies:
    - python=3.*
    - pip
    - ipykernel
    - matplotlib
    - scipy
    - xarray
    - cartopy
    - arm_pyart
    - wradlib
    - pip:
        - metpy
